basePath: /api
definitions:
  main.Address:
    description: Address and coordinates struct with a specific address and/or coordinates
    properties:
      lat:
        example: "55.190467"
        format: string
        type: string
      lon:
        example: "61.282494"
        format: string
        type: string
      result:
        example: г. Челябинск, ул. Чичерина, 1
        format: string
        type: string
    type: object
  main.AddressSearchRequest:
    description: single string request for inner usage
    properties:
      query:
        example: г. Челябинск, ул. Чичерина, 1
        format: string
        type: string
    type: object
  main.SearchResponse:
    description: response struct for inner usage
    properties:
      addresses:
        items:
          $ref: '#/definitions/main.Address'
        type: array
    type: object
host: localhost:8080
info:
  contact: {}
  description: test API server for hugoProxy
  title: HugoProxyWithYandexGeoApi
  version: "1.1"
paths:
  /address/geocode:
    post:
      consumes:
      - application/json
      description: Get address from coordinates
      parameters:
      - description: Address
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/main.Address'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.SearchResponse'
        "400":
          description: Bad Request
        "503":
          description: Service Unavailable
      summary: Get address from coordinates
      tags:
      - geocode
  /address/search:
    post:
      consumes:
      - application/json
      description: Get coordinates from address
      parameters:
      - description: AddressSearchRequest
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/main.AddressSearchRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.SearchResponse'
        "400":
          description: Bad Request
        "503":
          description: Service Unavailable
      summary: Get coordinates from address
      tags:
      - search
swagger: "2.0"
